#!/usr/bin/env python3
"""Generates HeadwindCore's WMM coefficient table from an official WMM.COF.

Usage: python3 scripts/build-wmm.py /path/to/WMM_2025.COF

Writes Packages/HeadwindCore/Sources/HeadwindCore/Geo/WMMCoefficients.swift.
The .COF format is NOAA/NCEI's: a header line `epoch model release`, then
`n m gnm hnm dgnm dhnm` rows, terminated by a line of 9s.
"""

import sys
from pathlib import Path


def main(cof_path):
    lines = Path(cof_path).read_text().splitlines()
    epoch, model, release = lines[0].split()

    rows = []
    for line in lines[1:]:
        if line.strip().startswith("9999"):
            break
        parts = line.split()
        if len(parts) != 6:
            continue
        n, m = int(parts[0]), int(parts[1])
        g, h, dg, dh = (float(x) for x in parts[2:])
        rows.append(f"        WMMRow(n: {n}, m: {m}, g: {g}, h: {h}, dg: {dg}, dh: {dh}),")

    out = Path(__file__).resolve().parents[1] / (
        "Packages/HeadwindCore/Sources/HeadwindCore/Geo/WMMCoefficients.swift"
    )
    out.write_text(f"""// Generated by scripts/build-wmm.py from {model} (epoch {epoch},
// released {release}). Official NOAA/NCEI World Magnetic Model coefficients —
// do not edit by hand; regenerate from a new WMM.COF each model release.

struct WMMRow {{
    let n: Int
    let m: Int
    let g: Double
    let h: Double
    let dg: Double
    let dh: Double
}}

enum WMMCoefficients {{
    static let epoch = {epoch}
    static let model = "{model}"
    static let rows: [WMMRow] = [
{chr(10).join(rows)}
    ]
}}
""")
    print(f"{model} epoch {epoch}: {len(rows)} coefficient rows -> {out}")


if __name__ == "__main__":
    main(sys.argv[1])
